catalog/urls.py
from django.conf.urls import url

from . import views

app_name = 'catalog'
urlpatterns = [
    url(r'^main_category/$', views.main_category, name='main_category_radio'),
    url(r'^ware_images/$', views.ware_images, name='ware_images'),
    url(r'^discounts/non-sale/$', views.DiscountListView.as_view(),
        name='discounts_non_sale'),
    url(r'^discounts/all/$', views.AllDiscountListView.as_view(),
        name='discounts_all'),
    url(r'^new-wares/$', views.NewWaresListView.as_view(), name='new_wares'),
    url(r'^sale/(?P<pk>[0-9]+)/$', views.SaleDetailView.as_view(),
        name='sale_detail'),
    url(r'^(?P<slug>[-\w]+)/$', views.CategoryDetailView.as_view(),
        name='detail'),
    url(r'^(?P<slug>[-\w]+)/list/$', views.CategoryListView.as_view(),
        name='list'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<pk>[0-9]+)/$',
        views.WareDetailView.as_view(), name='ware_detail'),
]

utils/models.py
from django.db.models import (
    BigIntegerField, Exists, OuterRef, QuerySet, Subquery)
from django.db.models.expressions import Col, F, OrderBy, RawSQL
from django.db.models.functions.base import Cast
from django.db.models.lookups import Exact
from django.db.models.query_utils import Q
from django.db.models.sql.where import AND

from .win_func import ArrayAggMult, DenseRank


class HierarchicalQuerySet(QuerySet):
    """QuerySet for working with tree-like structures.

    Applies all ordering to sibling elements instead of of whole query
    while preserving tree structure.
    Use set_root to add filtering for specific ancestor(s)
    Use regular filter/exclude to filter by parameter(s) that
    should be the same for entire tree/subtree (e.g. menu_id for
    menu items or post_id for comments).
    Use filter_tree/exclude_tree to filter by parameter(s) that
    will vary from element to element.
    """

    def __init__(self, *args, **kwargs):
        self._condition_count = 0
        super().__init__(*args, **kwargs)

    def _clone(self, *args, **kwargs):
        clone = super()._clone(*args, **kwargs)
        clone._condition_count = self._condition_count
        return clone

    def _fetch_all(self):
        if self._result_cache is None:
            self._result_cache = list(
                self._iterable_class(self._make_tree_qs()))
        if self._prefetch_related_lookups and not self._prefetch_done:
            self._prefetch_related_objects()

    def _get_limits(self):
        return {'low': self.query.low_mark, 'high': self.query.high_mark}

    def _make_tree_qs(self):
        flat_tree = self._from_subquery(self._default_manager.get_queryset(),
                                        self._make_path_qs())
        depth_field = self.model._closure_model._meta.get_field('depth')
        depth_col = Col(flat_tree.query.alias_prefix, depth_field)
        flat_tree.query.where.add(Exact(depth_col, 0), AND)
        flat_tree = flat_tree.order_by('path')
        flat_tree = flat_tree.annotate(path=self._get_col('path'),
                                       **self._get_user_annotations())
        flat_tree.query.set_limits(**self._get_limits())
        return flat_tree

    def _make_path_qs(self):
        select_fields = [self._get_col(x.column) for x
                        in self.query.get_meta().fields]
        select_fields.append(self._get_col('depth'))
        select_fields.extend(self._get_user_annotations().values())
        path_qs = self._default_manager.annotate(
            path=ArrayAggMult(
                Cast(self._get_col('parent_id'), BigIntegerField()),
                Cast(self._get_col('sib_order'), BigIntegerField()),
                partition_by=self._get_col('child_id'),
                order_by=OrderBy(self._get_col('depth'), descending=True))
        )
        path_qs = self._from_subquery(path_qs, self._make_sib_order_qs(),
                                      select=select_fields)
        return path_qs

    def _make_sib_order_qs(self):
        closure_ref = self.model._closure_parentref() + '__'
        clone = self._clone()
        # Resetting limit and ofset, they will be set on outermost query
        clone.query.low_mark = None
        clone.query.high_mark = None
        sib_order_qs = clone.annotate(
            sib_order=DenseRank(
                partition_by='parent_id', order_by=self._ordering,
                output_field=BigIntegerField()),
            child_id=F(closure_ref + 'child_id'),
            depth=F(closure_ref + 'depth')
        )
        return sib_order_qs

    def _from_subquery(self, outer_query, inner_query, select=[]):
        tb_alias = self.query.alias_prefix
        subqs = Subquery(inner_query)
        subqs.template += ' {}'.format(tb_alias)
        query = outer_query.query
        query.tables = [tb_alias]
        query.alias_refcount[tb_alias] = 1
        query.alias_map[tb_alias] = subqs
        if select:
            query.set_select(select)
        return outer_query

    def _get_col(self, col_name):
        return RawSQL(col_name, ())

    def _get_user_annotations(self):
        """Turns user-specified annotations into raw column names"""
        return {k: self._get_col(k) for k in self.query.annotations.keys()}

    def filter_tree(self, *args, for_all=True, **kwargs):
        """Filters out entire subtrees by parameters specified.

        If for_all is true and element does not match search criteria
        the element and all of it's subelements will not be included
        into result set.
        If for_all is false element will be included into result set
        if at least one of the ancestors does match search criteria.
        """
        return self._filter_or_exclude_tree(
            False, *args, for_all=for_all, **kwargs)

    def exclude_tree(self, *args, for_all=True, **kwargs):
        """Excluding version of filter_tree."""
        return self._filter_or_exclude_tree(
            True, *args, for_all=for_all, **kwargs)

    def _filter_or_exclude_tree(self, negate, *args, for_all=True, **kwargs):
        self._condition_count += 1
        closure_ref = self.model._closure_parentref() + '__child_id'
        outer_ref = {closure_ref: OuterRef('pk')}
        sub_qs = self._default_manager.get_queryset()
        if for_all:
            args_negated = [~Q(x) for x in args]
            kwargs_negated = [~Q(**{k:v}) for k, v in kwargs.items()]
            sub_qs = sub_qs.filter(*args_negated + kwargs_negated, **outer_ref)
            subquery = ~Exists(sub_qs)
        else:
            sub_qs = sub_qs.filter(*args, **outer_ref, **kwargs)
            subquery = Exists(sub_qs)
        filter_tree = 'filter_tree{}'.format(self._condition_count)
        clone = self._clone()
        clone = clone.annotate(**{filter_tree: subquery})
        if negate:
            clone = clone.exclude(**{filter_tree: True})
        else:
            clone = clone.filter(**{filter_tree: True})
        return clone

    def add_root(self, *args, **kwargs):
        qs = self._default_manager.get_queryset().filter(*args, **kwargs)
        closure_ref = self.model._closure_parentref() + '__parent_id'
        return self.filter_tree(**{closure_ref+'__in': qs}, for_all=False)

    @property
    def _default_manager(self):
        return self.query.get_meta().default_manager

    @property
    def _ordering(self):
        query = self.query
        if query.extra_order_by:
            ordering = query.extra_order_by
        elif not query.default_ordering:
            ordering = query.order_by
        else:
            ordering = (query.order_by or query.get_meta().ordering or [])
        return ordering if ordering else [self.query.get_meta().pk.column]

utils/forms.py
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.forms.models import ModelChoiceField, ModelChoiceIterator, ModelForm
from django.forms.widgets import Widget


class TreeModelChoiceIterator(ModelChoiceIterator):
    def __iter__(self):
        if self.field.empty_label is not None:
            yield ("", self.field.empty_label)
        queryset = self.queryset.all()
        for obj in queryset:
            yield self.choice(obj)


class TreeModelChoiceField(ModelChoiceField):
    """A ModelChoiceField with visual improvements for tree sructures."""
    iterator = TreeModelChoiceIterator

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.required = False
        self.null = True
        model = self.queryset.model
        self.queryset = model.hierarchy

    def label_from_instance(self, obj):
        return obj.depth_padded_name


class TreeModelForm(ModelForm):
    """A ModelForm with visual improvements for tree sructures."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.sentinel = self.instance._closure_sentinel_attr
        qs = self[self.sentinel].field.queryset
        self[self.sentinel].field.queryset = qs.exclude(
            **{'pk': self.instance.pk})

    def clean(self):
        cleaned_data = super().clean()
        pk = cleaned_data.get('pk')
        parent = cleaned_data.get(self.sentinel)
        if pk is not None and (pk == parent):
            msg = "Element can't refer to itself."
            self.add_error(self.sentinel, msg)
        return cleaned_data

    class Meta:
        field_classes = {
            'parent': TreeModelChoiceField,
        }


class AutoreplacingFormSetMixin:
    """
    Mixin for formsets that enables replacement of some of
    its fields if they do not match specified condition.

    autoreplace_conditions - list of tree-tuples:
     * Name of field to override.
     * Predicate function that can take 2 arguments: child
     value and parent model instance. Child field will use
     replacement value if predicate function returns False.
     * Replacement. Either name of attribute or
     method of parent model instance or an arbitrary
     value. Method is called without any arguments.
     * set_on_instance. If true, new_value will be set
     on form model instance instead of form.data
    """
    autoreplace_conditions = []

    def clean(self, *args, **kwargs):
        self.autoreplace()
        super().clean(*args, **kwargs)

    def autoreplace(self):
        forms = self.forms
        for form, index in zip(forms, range(len(forms))):
            if form.empty_permitted and not form.has_changed():
                continue
            for condition in self.autoreplace_conditions:
                name, predicate, replacement, set_on_instance = condition
                key = form.add_prefix(name)
                if not predicate(form.data.get(key), self.instance):
                    if (isinstance(replacement, str)
                            and hasattr(self.instance, replacement)):
                        new_value = getattr(self.instance, replacement)
                    else:
                        new_value = replacement
                    new_value = new_value() if callable(new_value) else new_value
                    if set_on_instance:
                        setattr(form.instance, name, new_value)
                    else:
                        form.data[key] = new_value
            form.full_clean()
        self.forms = forms


class ReadOnlyWidget(Widget):
    template_name = 'utils/widgets/read_only_widget.html'


class ReadOnlyField(ReadOnlyPasswordHashField):
    widget = ReadOnlyWidget

utils/templates/utils/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap -->
    {% block css %}
      <link href="{% static 'utils/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous">

      <link href="{% static 'utils/style.css' %}" rel="stylesheet">
    {% endblock css %}
    <title>{% block title %}Ткани, шторы, всё для шитья{% endblock %}</title>

    <!-- SEO -->
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
  </head>
  <body>
    <div class="container">
      <div class="d-none d-lg-none flex-column align-items-end position-absolute"
        id="pallet" style="right: 0px; top: 0px">
        <div>Фон <input type="color" id="pallet-bg"></div>
        <div>Меню <input type="color" id="pallet-fg"></div>
        <div>Текст <input type="color" id="pallet-font"></div> 
      </div>
      

      <header class="row mt-3 justify-content-between d-none d-xl-flex">
        <a class="col-3 text-uppercase d-flex align-items-center text-dark px-0 font-weight-bold"
          href="/" id="site-logo">
          <img src="{% static 'utils/images/logo.jpg' %}"
            alt="логотип" class="rounded mr-2" />
            Ткани, шторы,
            <br />
            всё для шитья
        </a>
        <address class="col-6 my-0 d-flex flex-column
          align-items-center justify-content-center text-center">
          <strong class="mw-100">
            Санкт-Петербург, Балканская площадь, дом 5 лит. О, корпус БАЛКАНСКИЙ-6, 2-ой этаж
          </strong>
          <strong>+7-921-882-28-09</strong>
        </address>
        <div class="col-2 d-flex flex-column px-0 work-time text-uppercase">
          <b>Мы ждём вас</b>
          <strong>Каждый день</strong>
          <strong>с 10:00 до 22:00</strong>
          <strong>Без обеда</strong>
        </div>
      </header>

      {% block menu_top %}
        <nav class="row navbar navbar-light navbar-expand-xl
          bg-menu mb-3 rounded shadow-sm fixed-top pallet-fg" id="menu-top">
          <button class="navbar-toggler border-0 px-1 px-sm-2" type="button"
            data-toggle="collapse" data-target="#menu-top-content">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="text-uppercase d-flex d-xl-none align-items-center
            text-dark px-0 mr-auto ml-2" href="/" id="site-logo-mobile">
            <img src="{% static 'utils/images/logo.jpg' %}"
              alt="логотип" class="rounded mr-2" />
              Ткани, шторы,
              <br />
              всё для шитья
          </a>
          <span class="d-xl-none pr-2 pr-sm-3" id="mobile-phone-num">+79218822809</span>
          <a href="tel:+79218822809" class="d-xl-none pr-1 pr-sm-2 text-muted">
            <i class="fas fa-phone"></i>
          </a>
          <address class="d-xl-none mb-0 text-center w-100">
            Санкт-Петербург, Балканская площадь. д. 5 лит. О,<br />
            корпус БАЛКАНСКИЙ-6, 2-ой этаж<br>
            <span class="font-weight-bold text-uppercase">Ежедневно с 10:00 до 22:00 без обеда</span>
          </address>

          <div class="collapse navbar-collapse" id="menu-top-content">
            <ul class="navbar-nav row flex-column col px-0 pt-2 m-auto">
              {% for menu_item in menu_top %}
                <li class="nav-item d-block col-xl text-xl-center px-xl-0">
                  {% if menu_item.url == request.path %}
                  <a href="{{ menu_item.url }}" class="nav-link py-1 active">
                  {% else %}
                  <a href="{{ menu_item.url }}" class="nav-link py-1 text-body pallet-font">
                  {% endif %}
                    {{ menu_item.name }}
                  </a>
                </li>
                {% if forloop.counter == 1 %}
                  <li class="nav-item d-block pl-3 d-xl-none" id="menu-mobile-catalog">
                    <button type="button" data-toggle="collapse"
                      data-target="#mobile-catalog" id='catalog-button'
                      class="btn btn-menu py-1 px-0 text-menu text-left w-100 pallet-font">
                        Каталог
                    </button>
                    <ul class="nav collapse py-0" id="mobile-catalog">
                      {% include "./catalog-menu.html" with menu_name='mobile' %}
                    </ul>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </nav>
      {% endblock menu_top %}

      <div class="row">
        {% block menu_left %}
          <nav class="col-3 pl-0 d-none d-xl-flex align-items-start" id="menu-left">
            <ul class="nav bg-menu py-2 pl-0 pr-2 rounded shadow-sm pallet-fg">
              <div class="w-100 d-flex justify-content-center mb-3">
                <span class="pl-2 text-center text-uppercase" id="catalog-sign">
                  Каталог
                </span>
              </div>
              {% include "./catalog-menu.html" with menu_name='left' %}
            </ul>
          </nav>
        {% endblock menu_left %}
          <div class="col col-xl-9" id="content">
            {% block breadcrumbs %}{% include "utils/breadcrumbs.html" %}{% endblock %}
            {% block content %}Base template text content{% endblock %}
          </div>
        </div>

    </div>
    {% block js-body-end %}
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
      <script src="{% static 'utils/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'utils/script.js' %}"></script>
    {% endblock js-body-end %}
  </body>
</html>

utils/templates/utils/breadcrumbs.html
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-transparent">
        <li class="breadcrumb-item">
          <a href="/" class="text-dark text-uppercase">Главная</a>
        </li>
        {% for crumb in breadcrumbs %}
          <li class="breadcrumb-item">
            {% if crumb.url is None %}
              <span class="font-weight-bold text-uppercase">{{ crumb.name }}</span>
            {% else %}
              <a href="{{ crumb.url }}" class="text-dark text-uppercase">{{ crumb.name }}</a>
            {% endif %}
          </li>
        {% endfor %}
      </ol>
    </nav>
  </div>
</div>

utils/templates/utils/catalog-menu.html
{% load project_common %}
{% tree menu_left as branches, node %}
  <li class="w-100 nav-item pl-2">
    <button type="button" data-toggle="collapse"
      data-target="#menu-{{ menu_name }}-{{ node.pk }}-children"
      class="btn btn-menu py-1 px-0 {% if node.parent_id %} py-1 {% else %} py-2 {% endif %}
      text-menu text-left w-100">
      <div class="caret caret-closed d-inline-block mx-1 paused"></div>
      <b class="text-uppercase">{{ node.name }}</b>
    </button>
    <ul class="nav collapse" id="menu-{{ menu_name }}-{{ node.pk }}-children">
      {{ branches }}
      {% if not node.parent_id %}
        <div class="top-level-separator my-2 mx-auto w-50"></div>
      {% endif %}
    </ul>
  </li>
{% leaf %}
  <li class="w-100 nav-item pl-3 leaf">
    <a href="{{ node.url }}" class="nav-link py-1 px-0 text-menu text-uppercase
      {% if node.url == request.path %} active {% endif %}">
      {% url 'catalog:new_wares' as new_wares_url %}
      {% if node.url == new_wares_url %}
        <b>{{ node.name }}</b>
      {% else %}
        {{ node.name }}
      {% endif %}
    </a>
  </li>
{% endtree %}

utils/templates/utils/image-gallery.html
{% load static %}
<div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="image-galleryLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="container">
      <div class="row">
        <div class="col d-flex justify-content-between align-items-center">
          {% if secondary_images %}
            <span class="arrow-left"></span>
          {% endif %}
          <img src="{% static 'utils/images/loader.gif' %}" alt="Loading..." id="loader" />
          <div class="slide-wrapper position-relative m-auto">
            <button type="button" class="close position-absolute" aria-label="Close"
              style="display: none;">
              <span aria-hidden="true">&times;</span>
            </button>
            <img class="sample-image rounded img-thumbnail" data-original-id="" src="" />
          </div>
          {% if secondary_images %}
            <span class="arrow-right"></span>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>